dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    - Uniswap/uniswap-v3-core@1.0.0
    - Uniswap/uniswap-v3-periphery@1.0.0
    
autofetch_sources: true
dotenv: .env
compiler:
    solc:
        version: 0.8.0
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
            - "@uniswap/v3-core=Uniswap/uniswap-v3-core@1.0.0"
            - "@uniswap/v3-periphery=Uniswap/uniswap-v3-periphery@1.0.0"
            